import { Workflow, WorkflowTemplate, ProcessComparison, ProjectContext } from '../types/workflow';

export const DEFAULT_PROJECT_CONTEXT: ProjectContext = {
  projectName: 'sample-flow',
  displayName: 'E-Commerce & Operations (sample-flow)',
  description: 'Main enterprise project context with orders, invoices, inventory, and notification functions.',
  schemas: [
    { name: 'orders', displayName: 'Orders Collection', fields: [{ name: 'orderId' }, { name: 'vendorId' }, { name: 'totalAmount' }, { name: 'stock_type' }, { name: 'customerEmail' }] },
    { name: 'invoices', displayName: 'Invoices Collection', fields: [{ name: '_id' }, { name: 'orderId' }, { name: 'amount' }, { name: 'status' }] },
    { name: 'inventory', displayName: 'Inventory Collection', fields: [{ name: 'sku' }, { name: 'quantity' }, { name: 'stock_type' }] },
    { name: 'asset_requests', displayName: 'Asset Requests Collection', fields: [{ name: 'requestId' }, { name: 'approver_response' }, { name: 'assetType' }] },
    { name: 'customers', displayName: 'Customers Collection', fields: [{ name: 'customerId' }, { name: 'email' }] }
  ],
  functions: [
    { name: 'NotifyVendorOnOrder', description: 'Dispatches dispatch alert email & webhook to vendor', parameters: [{ name: 'vendorId' }] },
    { name: 'SendOrderConfirmation', description: 'Sends order confirmation receipt with invoice PDF', parameters: [{ name: 'recipientEmail' }, { name: 'invoiceId' }] },
    { name: 'ValidateRequest', description: 'Verifies asset policy compliance & budget ceiling', parameters: [{ name: 'requestId' }] },
    { name: 'NotifyApprover', description: 'Pushes mobile authorization token to designated manager', parameters: [{ name: 'approverRole' }] },
    { name: 'RejectAndNotify', description: 'Generates adverse action policy note and emails applicant', parameters: [{ name: 'reason' }] }
  ],
  buttons: [
    { id: 'UpdateStockOperation', name: 'Update Inventory Operation', formId: 'inventoryForm', action: 'adjust_stock' },
    { id: 'ApproveButton', name: 'Approve Request Button', formId: 'approvalsForm', action: 'approve' },
    { id: 'RejectButton', name: 'Reject Request Button', formId: 'approvalsForm', action: 'reject' }
  ]
};

export const INITIAL_DEMO_TEXT = `When an order is placed, notify the vendor, create an invoice, update inventory if the stock type is physical, and send a confirmation.`;

export const MOCK_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'scenario-a-order-placed',
    title: 'Scenario A: Order Placed (Context Passing & STP)',
    category: 'E-Commerce & Orders',
    projectName: 'sample-flow',
    description: 'Triggered when an order is created. Dispatches vendor notification, generates invoice, checks stock type, and sends confirmation with generated invoice ID.',
    rawInput: INITIAL_DEMO_TEXT,
    tags: ['PS11_Scenario_A', 'OrderPlaced', 'ContextPassing']
  },
  {
    id: 'scenario-b-asset-approval',
    title: 'Scenario B: Asset Request Approval (Multi-Branching)',
    category: 'Operations & Approvals',
    projectName: 'sample-flow',
    description: 'Triggered on asset request update. Validates request, routes to approver, updates status & creates asset if approved, or rejects and notifies.',
    rawInput: `When an asset request is updated, validate the request, notify the approver. If approver response is approved update request status and create asset record. Otherwise reject and notify.`,
    tags: ['PS11_Scenario_B', 'Branching', 'Approvals']
  },
  {
    id: 'multi-workflow-chain',
    title: 'Multiple Independent Workflow Chain (PS11 Requirement)',
    category: 'Multi-Workflow Detection',
    projectName: 'sample-flow',
    description: 'Contains two distinct workflows in a single prompt: Order Placed and Order Cancelled.',
    rawInput: `When an order is placed notify the vendor and create an invoice.
When an order is cancelled trigger a refund and notify customer.`,
    tags: ['PS11_Multi_Workflow', 'ParallelChains']
  }
];

export const DEFAULT_MOCK_WORKFLOW: Workflow = {
  id: 'wf_scenario_order_placed',
  workflowId: 'wf_scenario_order_placed',
  workflowName: 'OrderPlaced',
  title: 'OrderPlaced (PS11 Scenario A)',
  description: 'AI-detected workflow for formCreate on orders with 4 orchestrated steps, context passing {{step-002._id}}, and conditional operation execution.',
  projectName: 'sample-flow',
  triggerEvent: {
    type: 'formCreate',
    schema: 'orders'
  },
  status: 'published',
  version: 1,
  editSource: 'detection',
  changeSummary: 'Initial workflow generated by AI detection',
  rawInput: INITIAL_DEMO_TEXT,
  confidence: 0.98,
  warnings: [],
  tags: ['PS11_Scenario_A', 'OrderPlaced', 'ContextPassing'],
  steps: [
    {
      stepId: 'step-001',
      name: 'Notify Vendor',
      order: 1,
      actionType: 'function',
      functionName: 'NotifyVendorOnOrder',
      candidate: 'NotifyVendorOnOrder',
      inputMapping: { vendorId: '{{trigger.vendorId}}', orderId: '{{trigger.orderId}}' },
      onSuccess: 'next',
      onFailure: 'abort',
      description: 'Calls NotifyVendorOnOrder custom function with vendor ID.'
    },
    {
      stepId: 'step-002',
      name: 'Create Invoice',
      order: 2,
      actionType: 'formCreate',
      schema: 'invoices',
      candidate: 'invoices',
      inputMapping: { orderId: '{{trigger.orderId}}', amount: '{{trigger.totalAmount}}', vendorId: '{{trigger.vendorId}}' },
      onSuccess: 'next',
      onFailure: 'abort',
      description: 'Creates new invoice record in invoices schema.'
    },
    {
      stepId: 'step-003',
      name: 'Update Inventory',
      order: 3,
      actionType: 'operation',
      formId: 'inventoryForm',
      buttonId: 'UpdateStockOperation',
      candidate: 'UpdateStockOperation',
      inputMapping: { orderId: '{{trigger.orderId}}', stock_type: '{{trigger.stock_type}}' },
      condition: { field: 'stock_type', operator: '==', value: 'physical' },
      onSuccess: 'next',
      onFailure: 'skip',
      description: 'Executes UpdateStockOperation button only if stock_type equals physical.'
    },
    {
      stepId: 'step-004',
      name: 'Send Confirmation',
      order: 4,
      actionType: 'function',
      functionName: 'SendOrderConfirmation',
      candidate: 'SendOrderConfirmation',
      inputMapping: { recipientEmail: '{{trigger.customerEmail}}', invoiceId: '{{step-002._id}}' },
      onSuccess: 'next',
      onFailure: 'skip',
      description: 'Consumes generated invoiceId from step-002 output and sends customer confirmation.'
    }
  ],
  actors: [
    { id: 'actor_1', name: 'Trigger Initiator', role: 'Event Source', color: '#3b82f6', stepCount: 1 },
    { id: 'actor_2', name: 'Automation Engine', role: 'System Orchestrator', color: '#06b6d4', stepCount: 4 }
  ],
  healthScore: {
    overall: 94,
    clarity: 96,
    decisionComplexity: 88,
    manualDependency: 92,
    efficiency: 95,
    ownershipClarity: 98
  },
  metrics: {
    stepCount: 6,
    actorCount: 3,
    decisionCount: 1,
    relationshipCount: 8,
    estimatedCycleTime: '240 ms',
    manualHandoffs: 0
  },
  nodes: [
    {
      id: 'node_trigger',
      type: 'triggerNode',
      position: { x: 60, y: 220 },
      data: {
        label: 'Order Placed',
        title: 'Order Placed',
        subtext: 'formCreate (orders)',
        schema: 'orders',
        category: 'trigger',
        status: 'active',
        description: 'Initiated when formCreate occurs on orders collection.'
      }
    },
    {
      id: 'step-001',
      type: 'actionNode',
      position: { x: 380, y: 110 },
      data: {
        label: 'Notify Vendor',
        title: 'Notify Vendor',
        subtext: 'Target: Vendors',
        stepId: 'step-001',
        order: 1,
        actionType: 'function',
        functionName: 'NotifyVendorOnOrder',
        candidate: 'NotifyVendorOnOrder',
        inputMapping: { vendorId: '{{trigger.vendorId}}', orderId: '{{trigger.orderId}}' },
        onSuccess: 'next',
        onFailure: 'abort',
        status: 'idle',
        duration: '40ms'
      }
    },
    {
      id: 'step-002',
      type: 'actionNode',
      position: { x: 380, y: 330 },
      data: {
        label: 'Create Invoice',
        title: 'Create Invoice',
        subtext: 'Target: Vendors/orders/payments',
        stepId: 'step-002',
        order: 2,
        actionType: 'formCreate',
        schema: 'invoices',
        candidate: 'invoices',
        inputMapping: { orderId: '{{trigger.orderId}}', amount: '{{trigger.totalAmount}}', vendorId: '{{trigger.vendorId}}' },
        onSuccess: 'next',
        onFailure: 'abort',
        status: 'idle',
        duration: '60ms'
      }
    },
    {
      id: 'node_decision',
      type: 'decisionNode',
      position: { x: 740, y: 200 },
      data: {
        label: 'Stock Type?',
        title: 'Stock Type?',
        conditionQuestion: 'Stock Type?',
        actor: 'Automation Engine',
        category: 'decision',
        branches: [
          { label: 'Physical → Update Inv', targetId: 'step-003' },
          { label: 'Digital → Skip', targetId: 'step-004' }
        ],
        status: 'idle'
      }
    },
    {
      id: 'step-003',
      type: 'actionNode',
      position: { x: 1100, y: 110 },
      data: {
        label: 'Update Inventory',
        title: 'Update Inventory',
        subtext: 'Conditional: if physical stock',
        stepId: 'step-003',
        order: 3,
        actionType: 'operation',
        formId: 'inventoryForm',
        buttonId: 'UpdateStockOperation',
        candidate: 'UpdateStockOperation',
        inputMapping: { orderId: '{{trigger.orderId}}', stock_type: '{{trigger.stock_type}}' },
        condition: { field: 'stock_type', operator: '==', value: 'physical' },
        onSuccess: 'next',
        onFailure: 'skip',
        status: 'idle',
        duration: '50ms'
      }
    },
    {
      id: 'step-004',
      type: 'actionNode',
      position: { x: 1460, y: 220 },
      data: {
        label: 'Send Confirmation',
        title: 'Send Confirmation',
        subtext: 'Target: Customer',
        stepId: 'step-004',
        order: 4,
        actionType: 'function',
        functionName: 'SendOrderConfirmation',
        candidate: 'SendOrderConfirmation',
        inputMapping: { recipientEmail: '{{trigger.customerEmail}}', invoiceId: '{{step-002._id}}' },
        onSuccess: 'next',
        onFailure: 'skip',
        status: 'idle',
        duration: '45ms'
      }
    },
    {
      id: 'node_complete',
      type: 'completionNode',
      position: { x: 1820, y: 220 },
      data: {
        label: 'Workflow Complete',
        title: 'Workflow Complete',
        subtext: '✓ 100% DAG Passed',
        category: 'completion',
        status: 'completed',
        description: 'All orchestrated steps completed successfully.'
      }
    }
  ],
  edges: [
    {
      id: 'e_trig_1',
      source: 'node_trigger',
      target: 'step-001',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'formCreate (orders)',
      data: { routeType: 'success' }
    },
    {
      id: 'e_trig_2',
      source: 'node_trigger',
      target: 'step-002',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'Parallel Trigger',
      data: { routeType: 'success' }
    },
    {
      id: 'e_1_dec',
      source: 'step-001',
      target: 'node_decision',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'Vendor Dispatched',
      data: { routeType: 'success' }
    },
    {
      id: 'e_2_dec',
      source: 'step-002',
      target: 'node_decision',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'Invoice Generated',
      data: { routeType: 'success' }
    },
    {
      id: 'e_dec_3',
      source: 'node_decision',
      target: 'step-003',
      sourceHandle: 'physical',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'If physical stock',
      data: { routeType: 'conditional' }
    },
    {
      id: 'e_dec_4',
      source: 'node_decision',
      target: 'step-004',
      sourceHandle: 'digital',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'If digital stock (Bypass)',
      data: { routeType: 'success' }
    },
    {
      id: 'e_3_4',
      source: 'step-003',
      target: 'step-004',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'Stock Adjusted',
      data: { routeType: 'success' }
    },
    {
      id: 'e_4_complete',
      source: 'step-004',
      target: 'node_complete',
      type: 'animatedFlowEdge',
      animated: true,
      label: 'Confirmation Sent',
      data: { routeType: 'success' }
    }
  ]
};

export const MOCK_COMPARISON_DATA: ProcessComparison = {
  asIs: {
    title: 'Current Standard Process (As-Is)',
    stepCount: 11,
    manualHandoffs: 4,
    approvalStages: 3,
    estimatedCycleTime: '3.5 - 5 Days',
    healthScore: 82,
    automationRate: '24%'
  },
  toBe: {
    title: 'AI-Optimized Process (To-Be)',
    stepCount: 4,
    manualHandoffs: 0,
    approvalStages: 1,
    estimatedCycleTime: '240 Milliseconds (100% STP)',
    healthScore: 96,
    automationRate: '98%'
  },
  improvements: [
    { metric: 'Cycle Latency Reduction', delta: '-99.9% Latency', percent: '-99.9%', positive: true },
    { metric: 'Step Optimization', delta: '-7 Steps', percent: '-63%', positive: true },
    { metric: 'Manual Handoff Elimination', delta: '-4 Handoffs', percent: '-100%', positive: true },
    { metric: 'Workflow Health Score', delta: '+14 Points', percent: '+17%', positive: true }
  ],
  transformationPoints: [
    {
      stage: 'Order Notification & Invoicing',
      before: 'Manual email to vendor and invoice generation taking 4 hours.',
      after: 'Automated NotifyVendorOnOrder & formCreate on invoices executing in 120ms with {{trigger.vendorId}}.'
    },
    {
      stage: 'Inventory Adjustment Gate',
      before: 'Warehouse clerk manually checks stock type flag.',
      after: 'Conditional operation executes UpdateStockOperation only when stock_type is physical.'
    },
    {
      stage: 'Receipt Confirmation',
      before: 'Admin copies invoice ID and emails customer.',
      after: 'SendOrderConfirmation automatically consumes {{step-002._id}} output.'
    }
  ]
};
