import mongoose from 'mongoose';

const StepConditionSchema = new mongoose.Schema({
  field: { type: String },
  operator: { type: String, enum: ['==', '!=', '>', '<', '>=', '<=', 'contains', 'exists'], default: '==' },
  value: { type: mongoose.Schema.Types.Mixed }
}, { _id: false });

const WorkflowStepSchema = new mongoose.Schema({
  stepId: { type: String, required: true },
  name: { type: String, required: true },
  order: { type: Number, required: true },
  actionType: {
    type: String,
    enum: ['function', 'formCreate', 'formUpdate', 'formDelete', 'operation'],
    required: true
  },
  functionName: { type: String },
  schema: { type: String },
  formId: { type: String },
  buttonId: { type: String },
  inputMapping: { type: mongoose.Schema.Types.Mixed, default: {} },
  condition: StepConditionSchema,
  onSuccess: { type: String, default: 'next' }, // 'next' or specific stepId
  onFailure: { type: String, default: 'abort' }, // 'abort' | 'skip' | specific stepId
  description: { type: String },
  candidate: { type: String }
}, { _id: false });

const NodeSchema = new mongoose.Schema({
  id: { type: String, required: true },
  type: { type: String, required: true }, // 'actionNode' | 'decisionNode' | 'actorNode' | 'documentNode' | 'milestoneNode' | 'operationNode'
  position: {
    x: { type: Number, default: 0 },
    y: { type: Number, default: 0 }
  },
  data: { type: mongoose.Schema.Types.Mixed }
}, { _id: false });

const EdgeSchema = new mongoose.Schema({
  id: { type: String, required: true },
  source: { type: String, required: true },
  target: { type: String, required: true },
  label: { type: String },
  type: { type: String, default: 'smoothstep' },
  animated: { type: Boolean, default: false },
  style: { type: mongoose.Schema.Types.Mixed },
  data: {
    condition: { type: String },
    routeType: { type: String, enum: ['success', 'failure', 'default'], default: 'success' },
    isCriticalPath: { type: Boolean, default: false }
  }
}, { _id: false });

const WorkflowSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true, index: true },
  workflowId: { type: String },
  workflowName: { type: String, required: true },
  title: { type: String },
  description: { type: String },
  projectName: { type: String, default: 'sample-flow', index: true },
  triggerEvent: {
    type: {
      type: String,
      enum: ['formCreate', 'formUpdate', 'formDelete', 'manual', 'webhook'],
      default: 'formCreate'
    },
    schema: { type: String, default: 'orders' },
    condition: { type: mongoose.Schema.Types.Mixed }
  },
  steps: [WorkflowStepSchema],
  nodes: [NodeSchema],
  edges: [EdgeSchema],
  status: {
    type: String,
    enum: ['draft', 'published', 'archived'],
    default: 'published',
    index: true
  },
  version: { type: Number, default: 1 },
  editSource: {
    type: String,
    enum: ['detection', 'manual', 'ai_agent'],
    default: 'detection'
  },
  changeSummary: { type: String, default: 'Initial workflow generated by AI detection' },
  actors: [{
    id: { type: String },
    name: { type: String },
    role: { type: String },
    color: { type: String },
    stepCount: { type: Number }
  }],
  decisions: [{
    id: { type: String },
    question: { type: String },
    options: [{ type: String }]
  }],
  bottlenecks: [{
    nodeId: { type: String },
    title: { type: String },
    severity: { type: String, enum: ['low', 'medium', 'high', 'critical'] },
    reason: { type: String },
    impact: { type: String },
    suggestedFix: { type: String }
  }],
  insights: [{
    id: { type: String },
    type: { type: String },
    title: { type: String },
    description: { type: String },
    relatedNodeIds: [{ type: String }],
    recommendation: { type: String },
    severity: { type: String, default: 'info' }
  }],
  healthScore: {
    overall: { type: Number, default: 85 },
    clarity: { type: Number, default: 92 },
    decisionComplexity: { type: Number, default: 78 },
    manualDependency: { type: Number, default: 70 },
    efficiency: { type: Number, default: 85 },
    ownershipClarity: { type: Number, default: 94 }
  },
  metrics: {
    stepCount: { type: Number, default: 0 },
    actorCount: { type: Number, default: 0 },
    decisionCount: { type: Number, default: 0 },
    relationshipCount: { type: Number, default: 0 },
    estimatedCycleTime: { type: String, default: '2.5 hours' },
    manualHandoffs: { type: Number, default: 2 }
  },
  rawInput: { type: String },
  tags: [{ type: String }],
  isOptimized: { type: Boolean, default: false }
}, {
  timestamps: true
});

export const Workflow = mongoose.models.Workflow || mongoose.model('Workflow', WorkflowSchema);
